/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doveshine;

import java.awt.event.ActionEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author benja
 */
public class Fees extends javax.swing.JFrame {

    Connection conn2 = null;
    PreparedStatement p3 = null;
    ResultSet r3 = null;

    public Fees() {
        initComponents();
        dateShow();
        timeShow();
        Tableshow();

    }

    void dateShow() {
        Date d1 = new Date();
        SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
        jTextField1datepay.setText(s1.format(d1));

    }

    void timeShow() {
        new Timer(0, (ActionEvent e) -> {
            Date d1 = new Date();
            SimpleDateFormat s1 = new SimpleDateFormat("hh:mm:ss");
            jTextField2timepay.setText(s1.format(d1));
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1tablefees = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1datepay = new javax.swing.JTextField();
        jTextField2timepay = new javax.swing.JTextField();
        jTextField3ffirstname = new javax.swing.JTextField();
        jTextField4lastname = new javax.swing.JTextField();
        jTextField5surname = new javax.swing.JTextField();
        jTextField7mobileno = new javax.swing.JTextField();
        jComboBox1term = new javax.swing.JComboBox<>();
        jComboBox2feesstatus = new javax.swing.JComboBox<>();
        jComboBox3class = new javax.swing.JComboBox<>();
        jButton1save = new javax.swing.JButton();
        jButton2generate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1search = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1print = new javax.swing.JButton();
        jButton1feeslogout = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jTextField1bal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox4month = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jComboBox4transport = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1tablefees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1tablefees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1tablefeesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1tablefees);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fees Payment Dashboard");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Date : (YEAR-MONTH-DATE)");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Time: (HOUR-MIN-SEC)");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Student FirstName:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Student LastName:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Student Surname:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Mobile Number:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Total Fees (KSH):");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Fees Paid (KSH):");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("FEES Balance (KSH):");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Class:");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Term:");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Fee Status:");

        jTextField1datepay.setEditable(false);
        jTextField1datepay.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jTextField2timepay.setEditable(false);
        jTextField2timepay.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jTextField3ffirstname.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextField3ffirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3ffirstnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3ffirstnameKeyReleased(evt);
            }
        });

        jTextField4lastname.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextField4lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4lastnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4lastnameKeyReleased(evt);
            }
        });

        jTextField5surname.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextField5surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5surnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5surnameKeyReleased(evt);
            }
        });

        jTextField7mobileno.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextField7mobileno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7mobilenoKeyPressed(evt);
            }
        });

        jComboBox1term.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox1term.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERM- ONE", "TERM- TWO", "TERM- THREE" }));
        jComboBox1term.setSelectedIndex(-1);

        jComboBox2feesstatus.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox2feesstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPLETE", "NOT- COMPLETE", "N/A" }));
        jComboBox2feesstatus.setSelectedIndex(-1);

        jComboBox3class.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox3class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLAYGROUP", "PP1", "PP2", "GRADE 1", "GRADE 2", "GRADE 3", "GRADE 4", "GRADE 5", "GRADE 6", "GRADE 7", "GRADE 8" }));
        jComboBox3class.setSelectedIndex(-1);

        jButton1save.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1save.setText("Save ");
        jButton1save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1saveActionPerformed(evt);
            }
        });

        jButton2generate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2generate.setText("Generate Receipt");
        jButton2generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2generateActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1search.setText("Search");
        jButton1search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1searchActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jScrollPane4.setViewportView(jTextPane1);

        jButton1print.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1print.setText("Print");
        jButton1print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1printActionPerformed(evt);
            }
        });

        jButton1feeslogout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1feeslogout.setText("Log out");
        jButton1feeslogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1feeslogoutActionPerformed(evt);
            }
        });

        jLabel14.setText("ADMISSION (KSH):");

        jLabel15.setText("INTERVIEW (KSH):");

        jLabel16.setText("TEA (KSH):");

        jLabel17.setText("LUNCH (KSH):");

        jLabel18.setText("ACTIVITY (KSH):");

        jLabel19.setText("REPORT BOOK (KSH):");

        jLabel20.setText("COMPUTER (KSH):");

        jLabel21.setText("RUBICS (KSH):");

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jComboBox2.setEditable(true);
        jComboBox2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox2.setSelectedIndex(-1);

        jComboBox3.setEditable(true);
        jComboBox3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox3.setSelectedIndex(-1);

        jComboBox5.setEditable(true);
        jComboBox5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox5.setSelectedIndex(-1);

        jComboBox6.setEditable(true);
        jComboBox6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox6.setSelectedIndex(-1);

        jComboBox7.setEditable(true);
        jComboBox7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox7.setSelectedIndex(-1);

        jComboBox8.setEditable(true);
        jComboBox8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox8.setSelectedIndex(-1);

        jComboBox9.setEditable(true);
        jComboBox9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox9.setSelectedIndex(-1);

        jComboBox10.setEditable(true);
        jComboBox10.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox10.setSelectedIndex(-1);

        jComboBox11.setEditable(true);
        jComboBox11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox11.setSelectedIndex(-1);

        jTextField1bal.setEditable(false);
        jTextField1bal.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel22.setText("MONTH:");

        jComboBox4month.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox4month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "JAN", "FEB", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUG", "SEPT", "OCT", "NOV", "DEC", " " }));
        jComboBox4month.setSelectedIndex(-1);

        jLabel23.setText("TRANSPORT (KSH):");

        jComboBox4transport.setEditable(true);
        jComboBox4transport.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox4transport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A" }));
        jComboBox4transport.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(694, 694, 694)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1feeslogout)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(772, 772, 772)
                        .addComponent(jButton1search))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jButton1save)
                                .addGap(35, 35, 35)
                                .addComponent(jButton2generate)
                                .addGap(48, 48, 48)
                                .addComponent(jButton1print, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel21)
                                                        .addGap(148, 148, 148))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addGap(152, 152, 152)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(129, 129, 129)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel22))
                                                .addGap(88, 88, 88)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox4transport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField1bal)
                                            .addComponent(jTextField5surname, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(jTextField4lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(jTextField3ffirstname)
                                            .addComponent(jComboBox1term, 0, 168, Short.MAX_VALUE)
                                            .addComponent(jComboBox2feesstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox3class, 0, 168, Short.MAX_VALUE)
                                            .addComponent(jTextField7mobileno, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox4month, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(29, 29, 29)
                                        .addComponent(jTextField1datepay, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(242, 242, 242)
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField2timepay, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(818, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1feeslogout)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1datepay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2timepay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addComponent(jTextField3ffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox3class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox4transport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1bal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1term, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox4month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2feesstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1search)
                    .addComponent(jButton3)
                    .addComponent(jButton1print)
                    .addComponent(jButton2generate)
                    .addComponent(jButton1save))
                .addContainerGap(573, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 406, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1saveActionPerformed
        // TODO add your handling code here:
        if (jTextField3ffirstname.getText().isEmpty() || jTextField4lastname.getText().isEmpty() || jTextField5surname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student Firstname,lastname or surname cannot be empty!!");
        } else if (jComboBox1.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Total fees amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox2.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Fees paid amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox3.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Admission amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox11.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Interview amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox10.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Tea amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox9.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Lunch amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox8.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Activity  amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox7.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Report Book amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox6.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Computer amount cannot be left empty.Choose N/A if Not applicable!!");
        } else if (jComboBox5.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Rubics amount cannot be left  empty.Choose N/A if Not applicable!!");
        } else if (jComboBox4transport.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Transport amount cannot be left  empty.Choose N/A if Not applicable!!");
        } else if (jComboBox3class.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You must choose a class!!");
        } else if (jComboBox1term.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You must choose a Term!!");
        } else if (jComboBox4month.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Month cannot be empty.Choose N/A if not applicable!!");

        } else if (jComboBox2feesstatus.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You must choose the Fee status!!");

        } else if (jTextField3ffirstname.getText().length() > 20 || jTextField4lastname.getText().length() > 20
                || jTextField5surname.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "All name fields should not exceed 20 characters!!");
        } else if (jTextField7mobileno.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "Mobile numbers should not exceed 10 characters!!");
        } else if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() != 0) {
            JOptionPane.showMessageDialog(null, "Operation failure,Total fees must be a value to perfom operation!!");
        } else if (jComboBox1.getSelectedIndex() != 0 && jComboBox2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Enter fees paid or 0 to continue operation!!");
        } else {

            try {
                balance();
                conn2 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
                String sql2;
                sql2 = "INSERT INTO feedetails "
                        + "( studentfirstname, studentlastname, studentsurname, mobileno, Totalfees, Feespaid,admission, interview, tea, lunch, activity, reportbook, computer, rubics,transport, Balance, Term,month, class, Feesstatus, Paymentdate, paymenttime) VALUES "
                        + "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                p3 = conn2.prepareStatement(sql2);
                p3.setString(1, jTextField3ffirstname.getText());
                p3.setString(2, jTextField4lastname.getText());
                p3.setString(3, jTextField5surname.getText());
                p3.setString(4, jTextField7mobileno.getText());
                p3.setString(5, String.valueOf(jComboBox1.getSelectedItem()));
                p3.setString(6, String.valueOf(jComboBox2.getSelectedItem()));
                p3.setString(7, String.valueOf(jComboBox3.getSelectedItem()));
                p3.setString(8, String.valueOf(jComboBox11.getSelectedItem()));
                p3.setString(9, String.valueOf(jComboBox10.getSelectedItem()));
                p3.setString(10, String.valueOf(jComboBox9.getSelectedItem()));
                p3.setString(11, String.valueOf(jComboBox8.getSelectedItem()));
                p3.setString(12, String.valueOf(jComboBox7.getSelectedItem()));
                p3.setString(13, String.valueOf(jComboBox6.getSelectedItem()));
                p3.setString(14, String.valueOf(jComboBox5.getSelectedItem()));
                p3.setString(15, String.valueOf(jComboBox4transport.getSelectedItem()));
                p3.setString(16, jTextField1bal.getText());

                p3.setString(17, String.valueOf(jComboBox1term.getSelectedItem()));
                p3.setString(18, String.valueOf(jComboBox4month.getSelectedItem()));
                p3.setString(19, String.valueOf(jComboBox3class.getSelectedItem()));
                p3.setString(20, String.valueOf(jComboBox2feesstatus.getSelectedItem()));
                p3.setString(21, jTextField1datepay.getText());
                p3.setString(22, jTextField2timepay.getText());
                p3.execute();
                JOptionPane.showMessageDialog(null, "Fee details successfully stored!!");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);

            }

            Tableshow();
    }//GEN-LAST:event_jButton1saveActionPerformed
    }
    private void jTable1tablefeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1tablefeesMouseClicked
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jTable1tablefeesMouseClicked

    private void jButton2generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2generateActionPerformed
        // TODO add your handling code here:

        jTextPane1.setText("********************************************************************\n");
        jTextPane1.setText(jTextPane1.getText() + "                             DOVESHINE  PRIMARY  SCHOOL            \n");
        jTextPane1.setText(jTextPane1.getText() + "                              Opposite  Midika  Kware            \n");
        jTextPane1.setText(jTextPane1.getText() + "                               Tel:0722-149-112            \n");
        jTextPane1.setText(jTextPane1.getText() + "                                   NAIROBI            \n");
        jTextPane1.setText(jTextPane1.getText() + "                          OFFICIAL  SCHOOL  RECEIPT        \n");
        jTextPane1.setText(jTextPane1.getText() + "********************************************************************\n");
         jTextPane1.setText(jTextPane1.getText() + "Date:  " + jTextField1datepay.getText() + "  " + "Time: " + jTextField2timepay.getText() + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Received from:  " + jTextField3ffirstname.getText() +" "+ jTextField4lastname.getText() +" "+ jTextField5surname.getText() + "\n\n");
 
        jTextPane1.setText(jTextPane1.getText() + "Student Class     :  " + String.valueOf(jComboBox3class.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Term              :  " + String.valueOf(jComboBox1term.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "For Month         :  " + String.valueOf(jComboBox4month.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Mobile No         :  " + jTextField7mobileno.getText() + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Total Fees (Ksh)  :  " + String.valueOf(jComboBox1.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Fee Paid (Ksh)    :  " + String.valueOf(jComboBox2.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Admission (Ksh)   :  " + String.valueOf(jComboBox3.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Interviews (Ksh)  :  " + String.valueOf(jComboBox11.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Tea (Ksh)         :  " + String.valueOf(jComboBox10.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Lunch (Ksh)       :  " + String.valueOf(jComboBox9.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Activity (Ksh)    :  " + String.valueOf(jComboBox8.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Report Book (Ksh) :  " + String.valueOf(jComboBox7.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Computer (Ksh)    :  " + String.valueOf(jComboBox6.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Rubics (Ksh)      :  " + String.valueOf(jComboBox5.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Transport (Ksh)   :  " + String.valueOf(jComboBox4transport.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + " Fees Balance(Ksh):  " + jTextField1bal.getText() + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Fee Status        :  " + String.valueOf(jComboBox2feesstatus.getSelectedItem()) + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "Signature:Headteacher/Bursar"+" "+ "........................" + "\n\n");
        jTextPane1.setText(jTextPane1.getText() + "*******                        OFFICIAL SCHOOL-FEES RECEIPT              ********\n");
        jTextPane1.setText(jTextPane1.getText() + "*******             NB:Fees paid is never refundable or transferable              ********\n");

    }//GEN-LAST:event_jButton2generateActionPerformed

    private void jButton1searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1searchActionPerformed
        // TODO add your handling code here:
        if (jTextField3ffirstname.getText().isEmpty() || jTextField4lastname.getText().isEmpty() || jTextField5surname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student Firstname,lastname or surname cannot be empty!!");
        } else if (jTextField3ffirstname.getText().length() > 20 || jTextField4lastname.getText().length() > 20
                || jTextField5surname.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "All name fields should not exceed 20 characters!!");
        } else {

            try {
                conn2 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
                String sql2;
                sql2 = " SELECT * FROM feedetails WHERE studentFirstName=? and studentLastName=?  and studentSurname=?";
                p3 = conn2.prepareStatement(sql2);
                p3.setString(1, jTextField3ffirstname.getText());
                p3.setString(2, jTextField4lastname.getText());
                p3.setString(3, jTextField5surname.getText());

                r3 = p3.executeQuery();
                jTable1tablefees.setModel(DbUtils.resultSetToTableModel(r3));

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);

            }
    }//GEN-LAST:event_jButton1searchActionPerformed
    }

    public void balance() {
        if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 0) {
            jTextField1bal.setText("N/A");
        } else if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() != 0) {
            JOptionPane.showMessageDialog(null, "Operation failure,Total fees must be a value to perfom operation!!");

        } else if (jComboBox1.getSelectedIndex() != 0 && jComboBox2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Enter fees paid or 0 to continue operation!!");

        } else {
            try {
                int ans;
                int num1 = Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));
                int num2 = Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
                ans = num1 - num2;
                jTextField1bal.setText(String.valueOf(ans));

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid number");

            }
        }
    }
    private void jButton1printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1printActionPerformed
        // TODO add your handling code here:
        try {
            jTextPane1.print();

        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1printActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        jTextField3ffirstname.setText(" ");
        jTextField4lastname.setText(" ");
        jTextField5surname.setText(" ");
        jTextField7mobileno.setText(" ");
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
        jTextField1bal.setText(" ");
        jComboBox3.setSelectedIndex(-1);
        jComboBox11.setSelectedIndex(-1);
        jComboBox10.setSelectedIndex(-1);
        jComboBox3class.setSelectedIndex(-1);
        jComboBox9.setSelectedIndex(-1);
        jComboBox8.setSelectedIndex(-1);
        jComboBox7.setSelectedIndex(-1);
        jComboBox6.setSelectedIndex(-1);
        jComboBox5.setSelectedIndex(-1);
        jComboBox4transport.setSelectedIndex(-1);
        jComboBox1term.setSelectedIndex(-1);
        jComboBox4month.setSelectedIndex(-1);
        jComboBox2feesstatus.setSelectedIndex(-1);
        jTextPane1.setText(" ");
        jTextPane1.setText(" ");
        jTextPane1.setText(" ");

        jTextPane1.setText(" ");
        jTextPane1.setText(" ");


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ffirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3ffirstnameKeyPressed
        // TODO add your handling code here:
        char d1 = evt.getKeyChar();
        if (Character.isLetter(d1) || Character.isISOControl(d1)) {
            // accept only letter
            jTextField3ffirstname.setEditable(true);
        } else {
            //deny character
            jTextField3ffirstname.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }

    }//GEN-LAST:event_jTextField3ffirstnameKeyPressed

    private void jTextField4lastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4lastnameKeyPressed
        // TODO add your handling code here:
        char d2 = evt.getKeyChar();
        if (Character.isLetter(d2) || Character.isISOControl(d2)) {
            // accept only letter
            jTextField4lastname.setEditable(true);
        } else {
            //deny character
            jTextField4lastname.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField4lastnameKeyPressed

    private void jTextField5surnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5surnameKeyPressed
        // TODO add your handling code here:
        char d3 = evt.getKeyChar();
        if (Character.isLetter(d3) || Character.isISOControl(d3)) {
            // accept only letter
            jTextField5surname.setEditable(true);
        } else {
            //deny character
            jTextField5surname.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField5surnameKeyPressed

    private void jTextField7mobilenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7mobilenoKeyPressed
        // TODO add your handling code here:
        char m1 = evt.getKeyChar();
        if (Character.isLetter(m1)) {
            //can't enter a textfield if entered character is not a number
            jTextField7mobileno.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter a number only!!");
        } else {
            jTextField7mobileno.setEditable(true);
        }
    }//GEN-LAST:event_jTextField7mobilenoKeyPressed

    private void jTextField3ffirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3ffirstnameKeyReleased
        // TODO add your handling code here:
        int position1a = jTextField3ffirstname.getCaretPosition();
        jTextField3ffirstname.setText(jTextField3ffirstname.getText().toUpperCase());
        jTextField3ffirstname.setCaretPosition(position1a);
    }//GEN-LAST:event_jTextField3ffirstnameKeyReleased

    private void jTextField4lastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4lastnameKeyReleased
        // TODO add your handling code here:
        int position1b = jTextField4lastname.getCaretPosition();
        jTextField4lastname.setText(jTextField4lastname.getText().toUpperCase());
        jTextField4lastname.setCaretPosition(position1b);


    }//GEN-LAST:event_jTextField4lastnameKeyReleased

    private void jTextField5surnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5surnameKeyReleased
        // TODO add your handling code here:
        int position1c = jTextField5surname.getCaretPosition();
        jTextField5surname.setText(jTextField5surname.getText().toUpperCase());
        jTextField5surname.setCaretPosition(position1c);

    }//GEN-LAST:event_jTextField5surnameKeyReleased

    private void jButton1feeslogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1feeslogoutActionPerformed
        // TODO add your handling code here:
        int pd = JOptionPane.showConfirmDialog(null, "Are you sure you want to  log out?", "Log out", JOptionPane.YES_NO_OPTION);
        if (pd == 0) {
            this.dispose();
            Login ld = new Login();
            ld.setVisible(true);
        }
    }//GEN-LAST:event_jButton1feeslogoutActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1KeyPressed

    public void Tableshow() {
        try {
            conn2 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
            String sql2;
            sql2 = " SELECT transactionId, studentfirstname, studentlastname, studentsurname, mobileno, Totalfees, Feespaid,admission, interview, tea, lunch, activity, reportbook, computer, rubics,transport, "
                    + "Balance, Term,month, class, Feesstatus, Paymentdate, TIME_FORMAT(paymenttime,'%h:%i:%s ')paymenttime FROM feedetails";
            p3 = conn2.prepareStatement(sql2);
            r3 = p3.executeQuery();
            jTable1tablefees.setModel(DbUtils.resultSetToTableModel(r3));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1feeslogout;
    private javax.swing.JButton jButton1print;
    private javax.swing.JButton jButton1save;
    private javax.swing.JButton jButton1search;
    private javax.swing.JButton jButton2generate;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox<String> jComboBox1term;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox<String> jComboBox2feesstatus;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox<String> jComboBox3class;
    private javax.swing.JComboBox jComboBox4month;
    private javax.swing.JComboBox jComboBox4transport;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1tablefees;
    private javax.swing.JTextField jTextField1bal;
    private javax.swing.JTextField jTextField1datepay;
    private javax.swing.JTextField jTextField2timepay;
    private javax.swing.JTextField jTextField3ffirstname;
    private javax.swing.JTextField jTextField4lastname;
    private javax.swing.JTextField jTextField5surname;
    private javax.swing.JTextField jTextField7mobileno;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
