/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doveshine;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author benja
 */
public class Registration extends javax.swing.JFrame {

    Connection conn1 = null;
    PreparedStatement p2 = null;
    ResultSet r2 = null;

    public Registration() {
        initComponents();
        studentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1FATHFNAME = new javax.swing.JTextField();
        jTextField1FLASTNAME = new javax.swing.JTextField();
        jTextField1FSURNMAE = new javax.swing.JTextField();
        jTextField1FMOBILENO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1FSTNAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1LASTNAME = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1SURNAME = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1stdclass = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2stdgender = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox1healthstatus = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1hcondition = new javax.swing.JTextArea();
        jTextField1dob = new com.toedter.calendar.JDateChooser();
        jTextField3doa = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField2UPI = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1MLNAME = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField1MSNAME = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField1MOBILENO = new javax.swing.JTextField();
        jTextField1MFNAME = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1GFNAME = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField1glastname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField2GSUNAME = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField2GMOBILE = new javax.swing.JTextField();
        jButton1stdinsert = new javax.swing.JButton();
        jButton1update = new javax.swing.JButton();
        jButton1stdelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1sttable = new javax.swing.JTable();
        jButton1search = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jButton1feespayment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setAutoscrolls(true);

        jTextField1FATHFNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1FATHFNAMEActionPerformed(evt);
            }
        });
        jTextField1FATHFNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1FATHFNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1FATHFNAMEKeyReleased(evt);
            }
        });

        jTextField1FLASTNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1FLASTNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1FLASTNAMEKeyReleased(evt);
            }
        });

        jTextField1FSURNMAE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1FSURNMAEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1FSURNMAEKeyReleased(evt);
            }
        });

        jTextField1FMOBILENO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1FMOBILENOKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("MOBILE NO:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("SURNAME:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("LAST NAME:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("FIRST NAME:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jTextField1FATHFNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1FSURNMAE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1FLASTNAME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1FMOBILENO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1FATHFNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1FLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1FSURNMAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1FMOBILENO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT REGISTRATION DASHBOARD");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("FIRST NAME:");

        jTextField1FSTNAME.setMaximumSize(new java.awt.Dimension(10, 10));
        jTextField1FSTNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FSTNAMEFocusLost(evt);
            }
        });
        jTextField1FSTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1FSTNAMEActionPerformed(evt);
            }
        });
        jTextField1FSTNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1FSTNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1FSTNAMEKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("LAST NAME:");

        jTextField1LASTNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1LASTNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1LASTNAMEKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("SURNAME:");

        jTextField1SURNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1SURNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1SURNAMEKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("CLASS:");

        jComboBox1stdclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLAYGROUP", "PP1", "PP2", "GRADE 1", "GRADE 2", "GRADE 3", "GRADE 4", "GRADE 5", "GRADE 6", "GRADE 7", "GRADE 8" }));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("GENDER:");

        jComboBox2stdgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setText("DATE OF BIRTH:");

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setText("DATE OF ADMISSION:");

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel25.setText("HEALTH STATUS:");

        jComboBox1healthstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WELL", "NOT-WELL" }));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel26.setText("HEALTH CONDITION :");

        jTextArea1hcondition.setColumns(20);
        jTextArea1hcondition.setLineWrap(true);
        jTextArea1hcondition.setRows(5);
        jTextArea1hcondition.setWrapStyleWord(true);
        jTextArea1hcondition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1hconditionKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTextArea1hcondition);

        jTextField1dob.setDateFormatString("yyyy-MM-dd");

        jTextField3doa.setDateFormatString(" yyyy-MM-dd");

        jLabel27.setText("AGE:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel28.setText("UPI:");

        jTextField2UPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2UPIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2UPIKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel22))
                        .addGap(171, 171, 171)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1FSTNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jComboBox2stdgender, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1LASTNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jTextField1SURNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jComboBox1stdclass, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1healthstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3doa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2UPI, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1FSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1LASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1SURNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1stdclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox2stdgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel22)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel24))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel28)
                                        .addComponent(jTextField2UPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField1dob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jTextField3doa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jComboBox1healthstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("MOTHER DETAILS");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("STUDENT DETAILS");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("FIRST NAME:");

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setText("LAST NAME:");

        jTextField1MLNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1MLNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1MLNAMEKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("SURNAME:");

        jTextField1MSNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1MSNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1MSNAMEKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setText("MOBILE NO:");

        jTextField1MOBILENO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1MOBILENOKeyPressed(evt);
            }
        });

        jTextField1MFNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1MFNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1MFNAMEKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1MLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1MFNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1MSNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1MOBILENO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1MFNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1MLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1MSNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1MOBILENO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setText("GUARDIAN DETAILS");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setText("FIRST NAME:");

        jTextField1GFNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1GFNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1GFNAMEKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setText("LAST NAME:");

        jTextField1glastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1glastnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1glastnameKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setText("SURNAME:");

        jTextField2GSUNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2GSUNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2GSUNAMEKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setText("MOBILE NO:");

        jTextField2GMOBILE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2GMOBILEKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1GFNAME)
                    .addComponent(jTextField1glastname)
                    .addComponent(jTextField2GSUNAME)
                    .addComponent(jTextField2GMOBILE, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField1GFNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField1glastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jTextField2GSUNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField2GMOBILE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton1stdinsert.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1stdinsert.setText("Save");
        jButton1stdinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1stdinsertActionPerformed(evt);
            }
        });

        jButton1update.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1update.setText("Update");
        jButton1update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1updateActionPerformed(evt);
            }
        });

        jButton1stdelete.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1stdelete.setText("Delete");
        jButton1stdelete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton1stdeleteMouseDragged(evt);
            }
        });
        jButton1stdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1stdeleteActionPerformed(evt);
            }
        });

        jTable1sttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1sttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1sttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1sttable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1952, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        jButton1search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1search.setText("Search");
        jButton1search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1searchActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jButton1feespayment.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1feespayment.setText("Fees Payment");
        jButton1feespayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1feespaymentActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("FATHER DETAILS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(197, 197, 197)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addGap(376, 376, 376)
                                    .addComponent(jLabel13)
                                    .addGap(192, 192, 192))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(jButton1stdinsert)
                                    .addGap(59, 59, 59)
                                    .addComponent(jButton1update)
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton1stdelete)
                                    .addGap(39, 39, 39)
                                    .addComponent(jButton1search)
                                    .addGap(46, 46, 46)
                                    .addComponent(Reset)
                                    .addGap(47, 47, 47)
                                    .addComponent(jButton1feespayment)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addComponent(jLabel23))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1974, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(527, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(631, 631, 631)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(572, 572, 572))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1stdinsert)
                            .addComponent(jButton1update)
                            .addComponent(jButton1stdelete)
                            .addComponent(jButton1search)
                            .addComponent(Reset)
                            .addComponent(jButton1feespayment))
                        .addGap(260, 260, 260))))
        );

        jScrollPane3.setViewportView(jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 2016, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1stdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1stdeleteActionPerformed
        // TODO add your handling code here:
        if (jTextField1FSTNAME.getText().isEmpty() || jTextField1LASTNAME.getText().isEmpty() || jTextField1SURNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student Firstname,lastname or surname cannot be empty!!");
        } else if (jTextField1FSTNAME.getText().length() > 20 || jTextField1LASTNAME.getText().length() > 20
                || jTextField1SURNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "All name fields should not exceed 20 characters!!");

        } else {
            int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Delete", JOptionPane.YES_NO_OPTION);
            if (c == 0) {
                try {
                    conn1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
                    String sql1;
                    sql1 = "DELETE FROM studentdetails WHERE studentFirstName=? and studentLastName=?  and studentSurname=?";
                    p2 = conn1.prepareStatement(sql1);
                    p2.setString(1, jTextField1FSTNAME.getText());
                    p2.setString(2, jTextField1LASTNAME.getText());
                    p2.setString(3, jTextField1SURNAME.getText());
                    p2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Student deleted successfully!!");

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);

                }
            }

        }
        studentTable();
    }//GEN-LAST:event_jButton1stdeleteActionPerformed

    private void jButton1stdeleteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1stdeleteMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1stdeleteMouseDragged

    private void jButton1updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1updateActionPerformed
        // TODO add your handling code here:
        if (jTextField1FSTNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student Firstname,lastname or surname cannot be empty!!");
        } else if (jTextField1LASTNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student lastname  cannot be empty!!");

        } else if (jTextField1SURNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student surname  cannot be empty!!");

        } else if (jTextField1dob.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Date of birth cannot be left empty!!");

        } else if (jTextField3doa.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Date of admission cannot be left empty!!");

        

        } else if (jTextField2UPI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "If student has no UPI write NILL,otherwise do not leave field empty!!");

        } else if (jTextField1FSTNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Student Firstname cannot exceed 20 characters!!");

        } else if (jTextField1LASTNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Student Lastname cannot exceed 20 characters!!");

        } else if (jTextField1SURNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Student Surname cannot exceed 20 characters!!");

        } else if (jTextField1.getText().length() > 3) {
            JOptionPane.showMessageDialog(null, "Student age cannot exceed 3 characters!!");

        } else if (jTextField2UPI.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "UPI a cannot exceed 10 characters!!");

        } else if (jComboBox1stdclass.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You must choose a class!!");

        } else if (jComboBox1healthstatus.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Health status cannot be left empty!!");

        }else if(jTextField1.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Student age  cannot be left empty!!");
            
            
    }else {
            try {
                conn1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
                String sql1;
                sql1 = " UPDATE `studentdetails` SET studentClass=?,studentGender=?,age=?,upi=?,dateofbirth=?,dateofadmission=?,fatherfirstname=?,fatherlastname=?,fathersurname=?,fathermobileno=?,motherfirstname=?,"
                        + "motherlastname=?,mothersurname=?,mothermobileno=?,guardianfirstname=?,guardianlastname=?,guardiansurname=?,guardianmobileno=?,healthstatus=?,healthcondition=? "
                        + "  WHERE  studentFirstName=? and studentLastName=?  and studentSurname=?";

                p2 = conn1.prepareStatement(sql1);
                p2.setString(21, jTextField1FSTNAME.getText());
                p2.setString(22, jTextField1LASTNAME.getText());
                p2.setString(23, jTextField1SURNAME.getText());

                p2.setString(1, String.valueOf(jComboBox1stdclass.getSelectedItem()));
                p2.setString(2, String.valueOf(jComboBox2stdgender.getSelectedItem()));

                p2.setString(3, jTextField1.getText());
                p2.setString(4, jTextField2UPI.getText());
                p2.setString(5, ((JTextField) jTextField1dob.getDateEditor().getUiComponent()).getText());
                p2.setString(6, ((JTextField) jTextField3doa.getDateEditor().getUiComponent()).getText());
                p2.setString(7, jTextField1FATHFNAME.getText());
                p2.setString(8, jTextField1FLASTNAME.getText());
                p2.setString(9, jTextField1FSURNMAE.getText());
                p2.setString(10, jTextField1FMOBILENO.getText());
                p2.setString(11, jTextField1MFNAME.getText());
                p2.setString(12, jTextField1MLNAME.getText());
                p2.setString(13, jTextField1MSNAME.getText());
                p2.setString(14, jTextField1MOBILENO.getText());
                p2.setString(15, jTextField1GFNAME.getText());
                p2.setString(16, jTextField1glastname.getText());
                p2.setString(17, jTextField2GSUNAME.getText());
                p2.setString(18, jTextField2GMOBILE.getText());
                p2.setString(19, String.valueOf(jComboBox1healthstatus.getSelectedItem()));
                p2.setString(20, jTextArea1hcondition.getText());

                p2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student successfully Updated!!");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        studentTable();
    }//GEN-LAST:event_jButton1updateActionPerformed

    private void jButton1stdinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1stdinsertActionPerformed
        // TODO add your handling code here:

        if (jTextField1FSTNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student Firstname,lastname or surname cannot be empty!!");
        } else if (jTextField1LASTNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student lastname  cannot be empty!!");

        } else if (jTextField1SURNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student surname  cannot be empty!!");

        } else if (jTextField1dob.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Date of birth cannot be left empty!!");

        } else if (jTextField3doa.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Date of admission cannot be left empty!!");

        } else if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student age  cannot be empty!!");

        } else if (jTextField2UPI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "If student has no UPI write NILL,otherwise do not leave field empty!!");

        } else if (jTextField1FSTNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Student Firstname cannot exceed 20 characters!!");

        } else if (jTextField1LASTNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Student Lastname cannot exceed 20 characters!!");

        } else if (jTextField1SURNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Student Surname cannot exceed 20 characters!!");

        } else if (jTextField1FATHFNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Father Firstname cannot exceed 20 characters!!");

        } else if (jTextField1FLASTNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Father Lastname cannot exceed 20 characters!!");

        } else if (jTextField1FSURNMAE.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Father Surname cannot exceed 20 characters!!");

        } else if (jTextField1MFNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Mother Firstname cannot exceed 20 characters!!");

        } else if (jTextField1MLNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Mother Lastname cannot exceed 20 characters!!");

        } else if (jTextField1MSNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Mother Surname cannot exceed 20 characters!!");

        } else if (jTextField1GFNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Guardian Firstname cannot exceed 20 characters!!");

        } else if (jTextField1glastname.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Guardian Lastname cannot exceed 20 characters!!");

        } else if (jTextField2GSUNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "Guardian Surname cannot exceed 20 characters!!");

        } else if (jTextArea1hcondition.getText().length() > 50) {
            JOptionPane.showMessageDialog(null, " Health condition should not exceed 50 characters!!");

        } else if (jTextField1.getText().length() > 3) {
            JOptionPane.showMessageDialog(null, "Student age cannot exceed 3 characters!!");

        } else if (jTextField2UPI.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "UPI a cannot exceed 10 characters!!");

        } else if (jComboBox1stdclass.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You must choose a class!!");

        } else if (jComboBox2stdgender.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You must choose a gender!!");

        } else if (jTextField1FMOBILENO.getText().length() > 10 || jTextField1MOBILENO.getText().length() > 10
                || jTextField2GMOBILE.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "Mobile numbers should not exceed 10 characters!!");
        } else if (jComboBox1healthstatus.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Health status cannot be left empty!!");

        } else {
            try {
                conn1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
                String sql1;
                sql1 = "INSERT INTO studentdetails(studentFirstName, studentLastName, studentSurname, studentClass, studentGender,age,upi,dateofbirth,dateofadmission, fatherfirstname, fatherlastname, fathersurname, fathermobileno, motherfirstname, motherlastname, mothersurname, mothermobileno, guardianfirstname, guardianlastname, guardiansurname, guardianmobileno,healthstatus,healthcondition) "
                        + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                p2 = conn1.prepareStatement(sql1);
                p2.setString(1, jTextField1FSTNAME.getText());
                p2.setString(2, jTextField1LASTNAME.getText());
                p2.setString(3, jTextField1SURNAME.getText());
                p2.setString(4, String.valueOf(jComboBox1stdclass.getSelectedItem()));
                p2.setString(5, String.valueOf(jComboBox2stdgender.getSelectedItem()));
                p2.setString(6, jTextField1.getText());
                p2.setString(7, jTextField2UPI.getText());
                p2.setString(8, ((JTextField) jTextField1dob.getDateEditor().getUiComponent()).getText());
                p2.setString(9, ((JTextField) jTextField3doa.getDateEditor().getUiComponent()).getText());
                p2.setString(10, jTextField1FATHFNAME.getText());
                p2.setString(11, jTextField1FLASTNAME.getText());
                p2.setString(12, jTextField1FSURNMAE.getText());
                p2.setString(13, jTextField1FMOBILENO.getText());
                p2.setString(14, jTextField1MFNAME.getText());
                p2.setString(15, jTextField1MLNAME.getText());
                p2.setString(16, jTextField1MSNAME.getText());
                p2.setString(17, jTextField1MOBILENO.getText());
                p2.setString(18, jTextField1GFNAME.getText());
                p2.setString(19, jTextField1glastname.getText());
                p2.setString(20, jTextField2GSUNAME.getText());
                p2.setString(21, jTextField2GMOBILE.getText());
                p2.setString(22, String.valueOf(jComboBox1healthstatus.getSelectedItem()));
                p2.setString(23, jTextArea1hcondition.getText());
                p2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student registration successfull");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);

            }
        }
        studentTable();
    }//GEN-LAST:event_jButton1stdinsertActionPerformed

    private void jTextField1FATHFNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1FATHFNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FATHFNAMEActionPerformed

    private void jTextField1FMOBILENOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FMOBILENOKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            //can't enter a textfield if entered character is not a number
            jTextField1FMOBILENO.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter a number only!!");

        } else {
            jTextField1FMOBILENO.setEditable(true);

        }
    }//GEN-LAST:event_jTextField1FMOBILENOKeyPressed

    private void jTextField1FSTNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FSTNAMEKeyPressed
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (Character.isLetter(d) || Character.isISOControl(d)) {
            //accept only letter
            jTextField1FSTNAME.setEditable(true);

        } else {
            // deny character
            jTextField1FSTNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1FSTNAMEKeyPressed

    private void jTextField1LASTNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1LASTNAMEKeyPressed
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (Character.isLetter(e) || Character.isISOControl(e)) {
            //accept only letter
            jTextField1LASTNAME.setEditable(true);

        } else {
            // deny character
            jTextField1LASTNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }

    }//GEN-LAST:event_jTextField1LASTNAMEKeyPressed

    private void jTextField1SURNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1SURNAMEKeyPressed
        // TODO add your handling code here:
        char f = evt.getKeyChar();
        if (Character.isLetter(f) || Character.isISOControl(f)) {
            //accept only letter
            jTextField1SURNAME.setEditable(true);

        } else {
            // deny character
            jTextField1SURNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }

    }//GEN-LAST:event_jTextField1SURNAMEKeyPressed

    private void jTextField1FATHFNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FATHFNAMEKeyPressed
        // TODO add your handling code here:
        char g = evt.getKeyChar();
        if (Character.isLetter(g) || Character.isISOControl(g)) {
            //accept only letter
            jTextField1FATHFNAME.setEditable(true);

        } else {
            // deny character
            jTextField1FATHFNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1FATHFNAMEKeyPressed

    private void jTextField1FLASTNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FLASTNAMEKeyPressed
        // TODO add your handling code here:
        char h = evt.getKeyChar();
        if (Character.isLetter(h) || Character.isISOControl(h)) {
            //accept only letter
            jTextField1FLASTNAME.setEditable(true);

        } else {
            // deny character
            jTextField1FLASTNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1FLASTNAMEKeyPressed

    private void jTextField1FSURNMAEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FSURNMAEKeyPressed
        // TODO add your handling code here:
        char i = evt.getKeyChar();
        if (Character.isLetter(i) || Character.isISOControl(i)) {
            //accept only letter
            jTextField1FSURNMAE.setEditable(true);

        } else {
            // deny character
            jTextField1FSURNMAE.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1FSURNMAEKeyPressed

    private void jTextField1MFNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1MFNAMEKeyPressed
        // TODO add your handling code here:
        char j = evt.getKeyChar();
        if (Character.isLetter(j) || Character.isISOControl(j)) {
            //accept only letter
            jTextField1MFNAME.setEditable(true);

        } else {
            // deny character
            jTextField1MFNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1MFNAMEKeyPressed

    private void jTextField1MLNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1MLNAMEKeyPressed
        // TODO add your handling code here:
        char k = evt.getKeyChar();
        if (Character.isLetter(k) || Character.isISOControl(k)) {
            //accept only letter
            jTextField1MLNAME.setEditable(true);

        } else {
            // deny character
            jTextField1MLNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1MLNAMEKeyPressed

    private void jTextField1MSNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1MSNAMEKeyPressed
        // TODO add your handling code here:
        char l = evt.getKeyChar();
        if (Character.isLetter(l) || Character.isISOControl(l)) {
            //accept only letter
            jTextField1MSNAME.setEditable(true);

        } else {
            // deny character
            jTextField1MSNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1MSNAMEKeyPressed

    private void jTextField1MOBILENOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1MOBILENOKeyPressed
        // TODO add your handling code here:
        char m = evt.getKeyChar();
        if (Character.isLetter(m)) {
            //can't enter a textfield if entered character is not a number
            jTextField1MOBILENO.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter a number only!!");

        } else {
            jTextField1MOBILENO.setEditable(true);

        }
    }//GEN-LAST:event_jTextField1MOBILENOKeyPressed

    private void jTextField2GMOBILEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2GMOBILEKeyPressed
        // TODO add your handling code here:
        char m1 = evt.getKeyChar();
        if (Character.isLetter(m1)) {
            //can't enter a textfield if entered character is not a number
            jTextField2GMOBILE.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter a number only!!");

        } else {
            jTextField2GMOBILE.setEditable(true);

        }
    }//GEN-LAST:event_jTextField2GMOBILEKeyPressed

    private void jTextField1GFNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1GFNAMEKeyPressed
        // TODO add your handling code here:
        char l1 = evt.getKeyChar();
        if (Character.isLetter(l1) || Character.isISOControl(l1)) {
            //accept only letter
            jTextField1GFNAME.setEditable(true);

        } else {
            // deny character
            jTextField1GFNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1GFNAMEKeyPressed

    private void jTextField1glastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1glastnameKeyPressed
        // TODO add your handling code here:
        char l2 = evt.getKeyChar();
        if (Character.isLetter(l2) || Character.isISOControl(l2)) {
            //accept only letter
            jTextField1glastname.setEditable(true);

        } else {
            // deny character
            jTextField1glastname.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField1glastnameKeyPressed

    private void jTextField2GSUNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2GSUNAMEKeyPressed
        // TODO add your handling code here:
        char l3 = evt.getKeyChar();
        if (Character.isLetter(l3) || Character.isISOControl(l3)) {
            jTextField2GSUNAME.setEditable(true);

        } else {
            // deny character
            jTextField2GSUNAME.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter letters only!!");
        }
    }//GEN-LAST:event_jTextField2GSUNAMEKeyPressed

    private void jTextField1FSTNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FSTNAMEKeyReleased
        // TODO add your handling code here:
        int position = jTextField1FSTNAME.getCaretPosition();
        jTextField1FSTNAME.setText(jTextField1FSTNAME.getText().toUpperCase());
        jTextField1FSTNAME.setCaretPosition(position);

    }//GEN-LAST:event_jTextField1FSTNAMEKeyReleased

    private void jTextField1FSTNAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FSTNAMEFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1FSTNAMEFocusLost

    private void jTextField1LASTNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1LASTNAMEKeyReleased
        // TODO add your handling code here:
        int position1 = jTextField1LASTNAME.getCaretPosition();
        jTextField1LASTNAME.setText(jTextField1LASTNAME.getText().toUpperCase());
        jTextField1LASTNAME.setCaretPosition(position1);
    }//GEN-LAST:event_jTextField1LASTNAMEKeyReleased

    private void jTextField1SURNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1SURNAMEKeyReleased
        // TODO add your handling code here:
        int position2 = jTextField1SURNAME.getCaretPosition();
        jTextField1SURNAME.setText(jTextField1SURNAME.getText().toUpperCase());
        jTextField1SURNAME.setCaretPosition(position2);
    }//GEN-LAST:event_jTextField1SURNAMEKeyReleased

    private void jTextField1FATHFNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FATHFNAMEKeyReleased
        // TODO add your handling code here:
        int position3 = jTextField1FATHFNAME.getCaretPosition();
        jTextField1FATHFNAME.setText(jTextField1FATHFNAME.getText().toUpperCase());
        jTextField1FATHFNAME.setCaretPosition(position3);
    }//GEN-LAST:event_jTextField1FATHFNAMEKeyReleased

    private void jTextField1FLASTNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FLASTNAMEKeyReleased
        // TODO add your handling code here:
        int position4 = jTextField1FLASTNAME.getCaretPosition();
        jTextField1FLASTNAME.setText(jTextField1FLASTNAME.getText().toUpperCase());
        jTextField1FLASTNAME.setCaretPosition(position4);
    }//GEN-LAST:event_jTextField1FLASTNAMEKeyReleased

    private void jTextField1FSURNMAEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FSURNMAEKeyReleased
        // TODO add your handling code here:
        int position5 = jTextField1FSURNMAE.getCaretPosition();
        jTextField1FSURNMAE.setText(jTextField1FSURNMAE.getText().toUpperCase());
        jTextField1FSURNMAE.setCaretPosition(position5);
    }//GEN-LAST:event_jTextField1FSURNMAEKeyReleased

    private void jTextField1MFNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1MFNAMEKeyReleased
        // TODO add your handling code here:
        int position6 = jTextField1MFNAME.getCaretPosition();
        jTextField1MFNAME.setText(jTextField1MFNAME.getText().toUpperCase());
        jTextField1MFNAME.setCaretPosition(position6);
    }//GEN-LAST:event_jTextField1MFNAMEKeyReleased

    private void jTextField1MLNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1MLNAMEKeyReleased
        // TODO add your handling code here:
        int position7 = jTextField1MLNAME.getCaretPosition();
        jTextField1MLNAME.setText(jTextField1MLNAME.getText().toUpperCase());
        jTextField1MLNAME.setCaretPosition(position7);
    }//GEN-LAST:event_jTextField1MLNAMEKeyReleased

    private void jTextField1MSNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1MSNAMEKeyReleased
        // TODO add your handling code here:
        int position8 = jTextField1MSNAME.getCaretPosition();
        jTextField1MSNAME.setText(jTextField1MSNAME.getText().toUpperCase());
        jTextField1MSNAME.setCaretPosition(position8);
    }//GEN-LAST:event_jTextField1MSNAMEKeyReleased

    private void jTextField1GFNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1GFNAMEKeyReleased
        // TODO add your handling code here:
        int position9 = jTextField1GFNAME.getCaretPosition();
        jTextField1GFNAME.setText(jTextField1GFNAME.getText().toUpperCase());
        jTextField1GFNAME.setCaretPosition(position9);
    }//GEN-LAST:event_jTextField1GFNAMEKeyReleased

    private void jTextField1glastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1glastnameKeyReleased
        // TODO add your handling code here:
        int position10 = jTextField1glastname.getCaretPosition();
        jTextField1glastname.setText(jTextField1glastname.getText().toUpperCase());
        jTextField1glastname.setCaretPosition(position10);
    }//GEN-LAST:event_jTextField1glastnameKeyReleased

    private void jTextField2GSUNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2GSUNAMEKeyReleased
        // TODO add your handling code here:
        int position11 = jTextField2GSUNAME.getCaretPosition();
        jTextField2GSUNAME.setText(jTextField2GSUNAME.getText().toUpperCase());
        jTextField2GSUNAME.setCaretPosition(position11);
    }//GEN-LAST:event_jTextField2GSUNAMEKeyReleased

    private void jButton1searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1searchActionPerformed
        // TODO add your handling code here:
        if (jTextField1FSTNAME.getText().isEmpty() || jTextField1LASTNAME.getText().isEmpty() || jTextField1SURNAME.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student Firstname,lastname or surname cannot be empty!!");
        } else if (jTextField1FSTNAME.getText().length() > 20 || jTextField1LASTNAME.getText().length() > 20
                || jTextField1SURNAME.getText().length() > 20) {
            JOptionPane.showMessageDialog(null, "All name fields should not exceed 20 characters!!");

        } else {
            try {
                conn1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
                String sql1;
                sql1 = "SELECT  studentFirstName, studentLastName, studentSurname, studentClass, studentGender, age, upi, dateofbirth,dateofadmission,fatherfirstname, fatherlastname, fathersurname, fathermobileno, motherfirstname, motherlastname, mothersurname, mothermobileno, guardianfirstname, guardianlastname, guardiansurname, guardianmobileno,healthstatus,healthcondition FROM studentdetails WHERE studentFirstName=? and studentLastName=?  and studentSurname=?";

                p2 = conn1.prepareStatement(sql1);
                p2.setString(1, jTextField1FSTNAME.getText());
                p2.setString(2, jTextField1LASTNAME.getText());
                p2.setString(3, jTextField1SURNAME.getText());
                r2 = p2.executeQuery();
                jTable1sttable.setModel(DbUtils.resultSetToTableModel(r2));

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);

            }
        }
    }//GEN-LAST:event_jButton1searchActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        jTextField1FSTNAME.setText("");
        jTextField1LASTNAME.setText("");
        jTextField1SURNAME.setText("");
        jTextField1FATHFNAME.setText("");
        jTextField1FLASTNAME.setText("");
        jTextField1FSURNMAE.setText("");

        jTextField1FMOBILENO.setText("");
        jTextField1MFNAME.setText("");
        jTextField1MLNAME.setText("");
        jTextField1MSNAME.setText("");
        jTextField2UPI.setText("");

        jTextField1MOBILENO.setText("");
        jTextField1GFNAME.setText("");
        jTextField1glastname.setText("");
        jTextField2GSUNAME.setText("");
        jTextField2GMOBILE.setText("");
        jComboBox1stdclass.setSelectedIndex(-1);
        jComboBox2stdgender.setSelectedIndex(-1);
        jTextField1dob.setCalendar(null);
        jTextField3doa.setCalendar(null);
        jComboBox1healthstatus.setSelectedIndex(-1);
        jTextArea1hcondition.setText("");
        jTextField1.setText(" ");


    }//GEN-LAST:event_ResetActionPerformed

    private void jTable1sttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1sttableMouseClicked
        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) jTable1sttable.getModel();
            int selectedRowIndex = jTable1sttable.getSelectedRow();
            jTextField1FSTNAME.setText(model.getValueAt(selectedRowIndex, 0).toString());
            jTextField1LASTNAME.setText(model.getValueAt(selectedRowIndex, 1).toString());
            jTextField1SURNAME.setText(model.getValueAt(selectedRowIndex, 2).toString());
            jTextField1.setText(model.getValueAt(selectedRowIndex, 5).toString());
            jTextField2UPI.setText(model.getValueAt(selectedRowIndex, 6).toString());
            //display date from jtable to jdatechooser
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(selectedRowIndex, 7).toString());
            jTextField1dob.setDate(date);

            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(selectedRowIndex, 8).toString());
            jTextField3doa.setDate(date1);

            jTextField1FATHFNAME.setText(model.getValueAt(selectedRowIndex, 9).toString());
            jTextField1FLASTNAME.setText(model.getValueAt(selectedRowIndex, 10).toString());
            jTextField1FSURNMAE.setText(model.getValueAt(selectedRowIndex, 11).toString());
            jTextField1FMOBILENO.setText(model.getValueAt(selectedRowIndex, 12).toString());
            jTextField1MFNAME.setText(model.getValueAt(selectedRowIndex, 13).toString());
            jTextField1MLNAME.setText(model.getValueAt(selectedRowIndex, 14).toString());
            jTextField1MSNAME.setText(model.getValueAt(selectedRowIndex, 15).toString());
            jTextField1MOBILENO.setText(model.getValueAt(selectedRowIndex, 16).toString());
            jTextField1GFNAME.setText(model.getValueAt(selectedRowIndex, 17).toString());
            jTextField1glastname.setText(model.getValueAt(selectedRowIndex, 18).toString());
            jTextField2GSUNAME.setText(model.getValueAt(selectedRowIndex, 19).toString());
            jTextField2GMOBILE.setText(model.getValueAt(selectedRowIndex, 20).toString());
            jTextArea1hcondition.setText(model.getValueAt(selectedRowIndex, 22).toString());
            String combo30 = model.getValueAt(selectedRowIndex, 3).toString();
            for (int j = 0; j < jComboBox1stdclass.getItemCount(); j++) {
                if (jComboBox1stdclass.getItemAt(j).equalsIgnoreCase(combo30)) {
                    jComboBox1stdclass.setSelectedIndex(j);
                }
            }

            String combo31 = model.getValueAt(selectedRowIndex, 4).toString();
            for (int k = 0; k < jComboBox2stdgender.getItemCount(); k++) {
                if (jComboBox2stdgender.getItemAt(k).equalsIgnoreCase(combo31)) {
                    jComboBox2stdgender.setSelectedIndex(k);
                }
            }
            String combo32 = model.getValueAt(selectedRowIndex, 21).toString();
            for (int l = 0; l < jComboBox1healthstatus.getItemCount(); l++) {
                if (jComboBox1healthstatus.getItemAt(l).equalsIgnoreCase(combo32)) {
                    jComboBox1healthstatus.setSelectedIndex(l);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jTable1sttableMouseClicked

    private void jButton1feespaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1feespaymentActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Fees fe = new Fees();
        fe.setVisible(true);

    }//GEN-LAST:event_jButton1feespaymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log out", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            this.dispose();
            Login lg = new Login();
            lg.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FSTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1FSTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FSTNAMEActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char m176 = evt.getKeyChar();
        if (Character.isLetter(m176)) {
            //can't enter a textfield if entered character is not a number
            jTextField1.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Age can only be a number!!");

            // } else {
            jTextField1.setEditable(true);

        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2UPIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2UPIKeyPressed
        // TODO add your handling code here:
        char m177 = evt.getKeyChar();
        if (Character.isLetterOrDigit(m177) || Character.isISOControl(m177)) {
            //code to accept only digits and letter
            jTextField2UPI.setEditable(true);
        } else {
            //if character is not letter or digit
            jTextField2UPI.setEditable(false);
        }
    }//GEN-LAST:event_jTextField2UPIKeyPressed

    private void jTextField2UPIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2UPIKeyReleased
        // TODO add your handling code here:
        int position111 = jTextField2UPI.getCaretPosition();
        jTextField2UPI.setText(jTextField2UPI.getText().toUpperCase());
        jTextField2UPI.setCaretPosition(position111);
    }//GEN-LAST:event_jTextField2UPIKeyReleased

    private void jTextArea1hconditionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1hconditionKeyReleased
        // TODO add your handling code here:
        int position112 = jTextArea1hcondition.getCaretPosition();
        jTextArea1hcondition.setText(jTextArea1hcondition.getText().toUpperCase());
        jTextArea1hcondition.setCaretPosition(position112);
    }//GEN-LAST:event_jTextArea1hconditionKeyReleased

    public void studentTable() {
        try {
            conn1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/doveshine", "benjaminkariuki", "uerPLk9!Xw4HFpc");
            String sql1;
            sql1 = "SELECT  studentFirstName, studentLastName, studentSurname, studentClass, studentGender,age,upi,dateofbirth,dateofadmission, fatherfirstname, fatherlastname, fathersurname, fathermobileno, motherfirstname, motherlastname, mothersurname, mothermobileno, guardianfirstname, guardianlastname, guardiansurname, guardianmobileno,healthstatus,healthcondition FROM studentdetails";
            p2 = conn1.prepareCall(sql1);
            r2 = p2.executeQuery();
            jTable1sttable.setModel(DbUtils.resultSetToTableModel(r2));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registration().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1feespayment;
    private javax.swing.JButton jButton1search;
    private javax.swing.JButton jButton1stdelete;
    private javax.swing.JButton jButton1stdinsert;
    private javax.swing.JButton jButton1update;
    private javax.swing.JComboBox<String> jComboBox1healthstatus;
    private javax.swing.JComboBox<String> jComboBox1stdclass;
    private javax.swing.JComboBox<String> jComboBox2stdgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1sttable;
    private javax.swing.JTextArea jTextArea1hcondition;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1FATHFNAME;
    private javax.swing.JTextField jTextField1FLASTNAME;
    private javax.swing.JTextField jTextField1FMOBILENO;
    private javax.swing.JTextField jTextField1FSTNAME;
    private javax.swing.JTextField jTextField1FSURNMAE;
    private javax.swing.JTextField jTextField1GFNAME;
    private javax.swing.JTextField jTextField1LASTNAME;
    private javax.swing.JTextField jTextField1MFNAME;
    private javax.swing.JTextField jTextField1MLNAME;
    private javax.swing.JTextField jTextField1MOBILENO;
    private javax.swing.JTextField jTextField1MSNAME;
    private javax.swing.JTextField jTextField1SURNAME;
    private com.toedter.calendar.JDateChooser jTextField1dob;
    private javax.swing.JTextField jTextField1glastname;
    private javax.swing.JTextField jTextField2GMOBILE;
    private javax.swing.JTextField jTextField2GSUNAME;
    private javax.swing.JTextField jTextField2UPI;
    private com.toedter.calendar.JDateChooser jTextField3doa;
    // End of variables declaration//GEN-END:variables
}
